### ISSUE TITLE
[REFACTOR] 기존 로고 삭제

### ISSUE THREAD

**Issue by Hanna922** [yourssu/Soomsil-Web#126]
# ISSUE ✅ : FEATURE

## 📖 DESCRIPTION
기존 로고 삭제

## ETC
쭌의 공

**Comment by nijuy** [comment]
이거 진짜 파일 하나 띡. 지우면 끝날 작업이니 따로 브랜치 안 파고 아무 작업에나 끼워도 괜찮을듯 합니다~~~!

**Comment by Hanna922** [comment]
다른 작업에 끼워넣을 거라면 PR 네이밍에도 같이 명시 부탁드려요

**Comment by 2wndrhs** [comment]
스노우볼이 이렇게나..
