### ISSUE TITLE
[REFACTOR] 서랍장 메인 화면 배너 이미지 교체

### ISSUE THREAD

**Issue by 2wndrhs** [yourssu/Soomsil-Web#148]
# ISSUE ✅ : REFACTOR

## 📖 DESCRIPTION

- 서랍장 메인 화면의 배너 이미지를 교체 
- #119 에서 삭제못한 기존 로고 파일 삭제하기

## Figma View

![image](https://github.com/yourssu/Soomsil-Web/assets/76615094/7b0e06e0-56a5-4cc0-9e7f-ecdec932d9f7)

## TODO

- [ ] 서랍장 메인 화면의 배너 이미지 교체
- [ ] 기존 로고 파일 삭제

## ETC

기타사항

**Comment by Hanna922** [comment]
로고 변경 지금 두 이슈로 나눠져있는데, 헷갈릴 것 같아서 이슈 148, 149 중 하나에서 진행 후 PR&이슈 네이밍에 반영 부탁드려요

**Comment by fecapark** [comment]
> 로고 변경 지금 두 이슈로 나눠져있는데, 헷갈릴 것 같아서 이슈 148, 149 중 하나에서 진행 후 PR&이슈 네이밍에 반영 부탁드려요

@2wndrhs 님이 진행하신다고 하네용
#149 에 반영하겠습니다

**Comment by 2wndrhs** [comment]
`ChangePasswordFrame`, `Header`, `Withdraw` 컴포넌트에 로고 파일 변경 사항이 반영이 안되어서 다시 오픈합니다🥲
