### ISSUE TITLE
[FIX] drawer detail 화면 image의 header 침범, main category dropdown 클릭 범위

### ISSUE THREAD

**Issue by Hanna922** [yourssu/Soomsil-Web#154]
# ISSUE ✅ : BUG

## 📖 Summary

- drawer detail 화면 image의 header 침범 사건
- drawer main 화면 category dropdown의 클릭 범위가 매우 넓음

## Photo

<img width="1440" alt="image" src="https://github.com/yourssu/Soomsil-Web/assets/84809236/2483e4d4-6404-497a-ab82-41e98c437c0d">

<img width="1440" alt="image" src="https://github.com/yourssu/Soomsil-Web/assets/84809236/c20ab651-94df-45b5-96e8-b4262e5159cd">

### 예상되는 동작을 설명해주세요.

헤더를 더 위로

**Comment by nijuy** [comment]
상세 페이지의 하단 영역 작업할 때 인지한 부분인데 ([관련 코멘트](https://github.com/yourssu/Soomsil-Web/pull/38#discussion_r1493696439))

이후 [삭제 모달](https://github.com/yourssu/Soomsil-Web/pull/80) 구현하면서 날아갔네요

서랍장 9차의 상세 페이지 작업을 제가 담당하고 있어서 같이 수정하겠습니다~

**Comment by Hanna922** [comment]
@nijuy #153 PR에서 같이 수정 가능하실까요? 마침 또 PR 제목이 '서랍장 UI 버그 수정'인지라..... 적합할 것 같다는 그런 느낌 ^^^~

**Comment by Hanna922** [comment]
main 화면에서 카테고리 드랍다운 클릭 범위가 비정상적이게 넓은 이슈도 있네용
Star Ranking 위 클릭해도 드랍다운이 열려요

**Comment by nijuy** [comment]
넵 확인했습니다!!
