### ISSUE TITLE
[FIX]: YDS 1.1.0 SimpleTextField 컴포넌트 suffix prop 관련 버그

### ISSUE THREAD

**Issue by 2wndrhs** [yourssu/Soomsil-Web#183]
# ISSUE ✅ : BUG

## 📖 Summary
YDS가 1.1.0 버전으로 업데이트 되면서 `SimpleTextField`의 `suffix` prop이 사라졌지만 여전히 `SimpleTextField`의 `suffix` prop을 사용하는 컴포넌트에서 에러가 발생 (https://github.com/yourssu/YDS-React/pull/74)

## Error Script
로컬 환경에서는 에러가 없었는데 빌드시에 에러가 발생해서 버그를 발견하였습니다.

### 그렇다면 왜 로컬에서는 에러가 발생하지 않았나?
YDS가 1.1.0으로 업데이트 되어 `pnpm install` 명령어로 YDS 1.1.0을 설치하였지만 **`pnpm`은 패키지를 자동으로 제거하지 않으므로** store에는 YDS 1.0.1이 남아있습니다.

> For example, during pnpm install, package foo@1.0.0 is updated to foo@1.0.1. **pnpm will keep foo@1.0.0 in the store**, as it does not automatically remove packages. If package foo@1.0.0 is not used by any other project on the system, it becomes unreferenced. Running pnpm store prune would remove foo@1.0.0 from the store.
> https://pnpm.io/cli/store#prune

따라서 `SimpleTextField` 컴포넌트의 suffix prop을 사용할 때 여전히 YDS 1.0.1의 `SimpleTextField` 컴포넌트를 참조할 수 있어 에러가 발생하지 않습니다. 

반면 빌드 시에는 `pnpm` 스토어에 YDS 1.0.1이 존재하지 않기 때문에 `SimpleTextField` 컴포넌트의 `suffix` prop을 사용하면 에러가 발생합니다😱

## Photo
- `SimpleTextField` 컴포넌트의 suffix prop을 사용하는 `PasswordInput.tsx`, `EmailAuth.tsx`, `EmailForm.tsx`에서 에러가 발생
<img width="1184" alt="image" src="https://github.com/yourssu/Soomsil-Web/assets/76615094/1c3dc031-7669-439e-9525-7f0d354269db">

## ETC
- YDS 버전 업데이트 시 `pnpm prune` 이나 `pnpm store prune` 명령어로 이전 버전의 YDS를 제거하도록 해야할 것 같네요🤔

**Comment by Hanna922** [comment]
ㅋㅋㅋㅋㅋ...🙄 이거 YDS 쪽에서 해결 할게요

**Comment by Hanna922** [comment]
우선 Soomsil에서 SimpleTextField에 suffix를 사용하고 있는 코드는 모두 제거해야 할 것 같네요
사실상 SuffixTextField, PasswordTextField로 변환하면 되는 작업들이라 #182 에서 같이 해결하면 좋을 것 같아요
@fecapark 혹시 요기 `PasswordInput.tsx`, `EmailAuth.tsx`, `EmailForm.tsx` 3군데에서 사용하고 있는 SimpleTextField도 변경 해주실 수 있으실까용?

**Comment by nijuy** [comment]
천재개발자

**Comment by fecapark** [comment]
> 우선 Soomsil에서 SimpleTextField에 suffix를 사용하고 있는 코드는 모두 제거해야 할 것 같네요 사실상 SuffixTextField, PasswordTextField로 변환하면 되는 작업들이라 #182 에서 같이 해결하면 좋을 것 같아요 @fecapark 혹시 요기 `PasswordInput.tsx`, `EmailAuth.tsx`, `EmailForm.tsx` 3군데에서 사용하고 있는 SimpleTextField도 변경 해주실 수 있으실까용? (바쁘시면 제가 해도 됨)

일단 자고 바로 진행하겠슴당
