### ISSUE TITLE
[FEAT] 헤더 프로필 아이콘 드롭다운 메뉴 연결

### ISSUE THREAD

**Issue by 2wndrhs** [yourssu/Soomsil-Web#197]
# ISSUE ✅ : FEATURE

## 📖 DESCRIPTION
- 헤더 프로필 아이콘 클릭 시 보여지는 드롭다운 메뉴 구현하기

## Figma View
<img width="140" alt="image" src="https://github.com/yourssu/Soomsil-Web/assets/76615094/76957dab-0f97-4a9e-9842-a98ee91fdd70">

## TODO

- [ ] 드롭다운 메뉴 구현
- [ ] 로그아웃 확인 모달 구현

## ETC

기타사항
🎸

**Comment by Hanna922** [comment]
드랍다운 이미 있는 거 아닌가요?

**Comment by 2wndrhs** [comment]
오잉 없을걸요..?
<img width="567" alt="image" src="https://github.com/yourssu/Soomsil-Web/assets/76615094/94d5d85f-22f5-4af9-b01f-5d4a0837cdf1">
여기 프로필 아이콘 누르면 나오는 메뉴라

**Comment by Hanna922** [comment]
아하 홈 프로필 눌렀을 때 나오는 드랍다운이랑 완전 동일하게 보이는데 그럼 연결만 하면 되지 않을까용

**Comment by 2wndrhs** [comment]
이미 있구나 야호
