### ISSUE TITLE
[FIX]: 회원탈퇴 이후 유저 정보가 남아있는 문제

### ISSUE THREAD

**Issue by nijuy** [yourssu/Soomsil-Web#204]
# ISSUE ✅ : BUG

## 📖 Summary

회원 탈퇴를 했는데 유저 정보가 남아있어요

## Error Script

토큰 삭제는 `postWithdraw`에서 하는데 `LoginState`랑 `UserState` 초기화하는 코드가 없어요

## Photo

![withdraw_error](https://github.com/yourssu/Soomsil-Web/assets/87255462/27470697-3d1a-4792-a995-cbfbb9c473cb)

**Comment by ssolfa** [comment]
헉 LoginState랑 UserState도 있군요,,, 탈퇴는 되는데 유저 정보가 남는 상태죠?! 제가 맡을까요??

**Comment by nijuy** [comment]
당신최고야 당신달콤햐

**Comment by ssolfa** [comment]
버그야 집에 같이 가자~~~,,,,,,,,
