### ISSUE TITLE
[FIX]: Footer에 버전이 명시되지 않은 문제

### ISSUE THREAD

**Issue by 2wndrhs** [yourssu/Soomsil-Web#265]
# ISSUE ✅ : BUG

## 📖 Summary

 Footer에 버전이 명시되지 않은 문제

## Photo

![image](https://github.com/user-attachments/assets/310a2daa-d427-405a-949f-1b66c92088fd)

## ETC

Footer에 버전이 명시되어 있어야 함 -> 근데 서랍장에만 Footer가 있는게 맞나..?

**Comment by seocylucky** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ일단 피그마상 저렇게 되어있긴 한데.... 서랍장에만 있는게 또 생각해보니 이상한 것 같기도
