### ISSUE TITLE
[FEAT] 서랍장 응답데이터 별 카드 컴포넌트 레이아웃 작업 + 서비스 수정 및 삭제 드롭다운 작업

### ISSUE THREAD

**Issue by seocylucky** [yourssu/Soomsil-Web#29]
# ISSUE ✅ : FEATURE

## 📖 DESCRIPTION
서랍장 tf에 사용되는 카드 컴포넌트들의 레이아웃 작업과 카드 컴포넌트에서 이용될 서비스 수정 및 삭제 컴포넌트 작업할 예정입니다.

## Figma View
서랍장 tf에 사용되는 카드 컴포넌트들의 레이아웃 작업입니다.
<응답 데이터가 있을 때>
![image](https://github.com/yourssu/Soomsil-Web/assets/94633589/543ebe1f-fc74-42b8-bee1-3defe73e85e7)

<응답 데이터가 없을 때>
![image](https://github.com/yourssu/Soomsil-Web/assets/94633589/5b69c389-138a-4738-98f9-a553f2e65734)

카드 컴포넌트에서 이용될 서비스 수정 및 삭제 컴포넌트 작업입니다.
![image](https://github.com/yourssu/Soomsil-Web/assets/94633589/413760ad-c76b-48be-bd8a-ed3f8c291f66)

## TODO
- [x] 카드 컴포넌트 레이아웃
- [x] 응답 데이터가 없을 때는 없습니다 컴포넌트 보여주기

## ETC
검색 결과가 없을 시 공통 텍스트로 통일하기로 결정이 난 상태. 추후 디자인 수정이 완료되면 그것에 맞게 반영하기
검색 결과가 없을 시 서비스 등록 버튼도 밑에 추가

<예시 화면>
<img width="256" alt="image" src="https://github.com/yourssu/Soomsil-Web/assets/94633589/a3aa1500-79f4-48f0-9373-d5609ab1a92c">

**Comment by JjungminLee** [comment]
🍒님 혹시 
<img width="473" alt="image" src="https://github.com/yourssu/Soomsil-Web/assets/85864699/98fb59c0-1ebe-40b4-ae5c-1d30441487ae">
요거 많이 급할까유? 제가 로그인 만들면서 드롭다운을 만들었는데  좀 더 공용컴포넌트로 쓸수 있게 몇줄 고치면 서랍장에서도 쓸수 있을것 같아서유! 이번주까지 해볼게용

**Comment by seocylucky** [comment]
오오 급하지 않아요!! 그럼 저부분은 일단 작업 보류하고 다른거 작업 먼저 하구 있겠습니다ㅎㅎㅎ 감사해요><
