### ISSUE TITLE
[FEAT] Home화면 서랍장 랭킹 컴포넌트

### ISSUE THREAD

**Issue by AAminha** [yourssu/Soomsil-Web#3]
# ISSUE ✅ : Home화면 서랍장 랭킹 컴포넌트 퍼블리싱

## 📖 DESCRIPTION
Home 화면의 서랍장 랭킹 컴포넌트 퍼블리싱 구현

## Figma View
![image](https://github.com/yourssu/Soomsil-Web/assets/87255791/f2f5621e-f5e3-4259-8a2a-f4c86f02a315)

## TODO
- [x] 서랍장 랭킹 컴포넌트 구현
  - [x] Bori가 만들어준 Card 컴포넌트로 구성

## ETC
기타사항

**Comment by nijuy** [comment]
@AAminha 

사진에 있는 랭킹 아이템(?) 컴포넌트가 서랍장 컴포넌트랑 엄청 유사해서 공통 컴포넌트로 만들어도 될 거 같은데 어떻게 생각하세요??

![image](https://github.com/yourssu/Soomsil-Web/assets/87255462/b59bfcf0-60b9-4c87-8731-f582bb99e625)

**Comment by AAminha** [comment]
아하 그렇네요!! 공통으로 해도 되는 부분인 것 같아요. 그러면 누가 담당할지도 얘기해봐야겠네용... 서랍장TF에서 해당 컴포넌트 구현하시는 게 좋을 것 같다고 생각하시나욤?!

**Comment by nijuy** [comment]
짜잔~ 제가 서랍장 회의로,,, 잠시 사라졌다가 나타났습니다
어떻게 구현하느냐에 따라 담당자가 달라질 거 같다는 생각,,👀 

혹시 미나 많..이 바쁜가요? 제가 YDS랑 Drawer를 같이 해야 해서. 엉엉. 가능하다면,, 맡아주실 수,,
[합성 컴포넌트 패턴](https://fe-developers.kakaoent.com/2022/220731-composition-component/)으로 구현하게 된다면 썸네일 같이 서랍장에서만 추가되는 부분은 제가 서브 컴포넌트 만들어서 쓸게요..! 공통 부분만 만들어주셔도.

**Comment by AAminha** [comment]
여행 중이라 저도 이제서야 짜잔~~ㅎㅎㅎ 그렇다면 제가 하도록 할게용!!!
