### ISSUE TITLE
[REFACTOR] 검색 키워드 컴포넌트 통합

### ISSUE THREAD

**Issue by AAminha** [yourssu/Soomsil-Web#46]
# ISSUE ✅ : FEATURE

## 📖 DESCRIPTION
Home에서의 `SearchKeyword` 컴포넌트와 Search의 `RealTimeKeyword` 컴포넌트를 공통 컴포넌트로 통합하여 재사용 합니다.

### Home
![image](https://github.com/yourssu/Soomsil-Web/assets/87255791/0625fba7-2cd4-49ce-b9ad-0800167a9e58)

### Search
![image](https://github.com/yourssu/Soomsil-Web/assets/87255791/345e39f0-e2a6-427b-b4b9-6e6e1f5dfe33)

## TODO
- [ ] 컴포넌트 통합
## ETC
기타사항

**Comment by indianaPoly** [comment]
디자인 팀한테 요청할 사항: 텍스트 내용 및 폰트 통일 논의 부탁

**Comment by owl1753** [comment]
제가 이 task 맡기로 했습니당 [home tf task 분배](https://www.notion.so/yourssu/soomsil-v2-home-3721961afcdf4497b64265865de5f86c?pvs=4)
