### ISSUE TITLE
[FIX] Search에서 발생하는 DOM Warning, path error 해결

### ISSUE THREAD

**Issue by Hanna922** [yourssu/Soomsil-Web#58]
# ISSUE ✅ : FIX

Search TF에서 발생하는 style.ts DOM Warning을 해결
component, components 중복 분리
path error 해결

## 📖 DESCRIPTION
Dropdown dom 문제 해결하다 search 쪽도 발견해서 같이 작업할게요...!

**Comment by nijuy** [comment]
이슈만 판다는 줄 알았는데 작업하겠다는 말이었군요??? 이사람.... 이사람 유노윤호다
