### ISSUE TITLE
[FEAT] 서랍장 등록 웹뷰 디바이스 반응형 조절

### ISSUE THREAD

**Issue by Hanna922** [yourssu/Soomsil-Web#66]
# ISSUE ✅ : 서랍장 등록 페이지(웹뷰) 디바이스 레이아웃 조절

### 현재 존재하는 문제
width 390px을 기준으로 media query를 작성중이기 때문에 iPhone XR(414), iPhone 14 Pro Max(430)의 경우 웹 화면이 띄워집니다. => 레이아웃 문제 발생

![image_720](https://github.com/yourssu/Soomsil-Web/assets/84809236/974aea02-407d-433d-92fd-dd1f8c0e54f5)

### 기준을 430px(26.875rem)으로 두었을 때
|14 Pro Max|12 Pro|
|--|--|
|![image_720](https://github.com/yourssu/Soomsil-Web/assets/84809236/ed2636d8-b02c-407a-952e-dc4834a63ad5)|![image_720](https://github.com/yourssu/Soomsil-Web/assets/84809236/75124b26-415f-466e-a88d-da0315f92ef3)|

=> 기준을 크게 잡아도 디자인에 문제가 없기 때문에, 기준은 크게 가져가는 것이 맞습니다.

### 고민되는 점
모바일에서는 기본적으로 상대단위를 통해 기기별 크기 대응을 하는 상태입니다.
현재 서랍장 등록 페이지 코드는 모두 rem 단위이기 때문에, 모바일 기기에서 등록 페이지 진입 시 컴포넌트의 크기가 달라보일 수 있다는 점이 고민입니다.
=> 상대단위를 써야할까,,,,🤔

## ETC
@nijuy @2wndrhs @seocylucky 의견 부탁드려요,,,,,,

**Comment by seocylucky** [comment]
저는 미디어 쿼리 별로 상대단위 쓰는 게 더 좋을 것 같긴 합니당
근데 일일이 또 추가하는 것도 일이니까... 430을 기준으로 두는 것도 사진 보니까 나쁠 건 없을 거 같아요!!!!

**Comment by Hanna922** [comment]
@nijuy @2wndrhs 의견 남겨주세용~!
**미디어 쿼리 내에서 상대단위까지 작업 vs 일단 미디어 쿼리 기준만 크게 설정**

**Comment by nijuy** [comment]
### 1. 모바일 breakpoint 수정
    
기준을 더 크게 잡아야 한다는 점에는 동의하나, 430px보다 더 여유있게 키우는 건 어떠세요?
에뮬레이터로 확인한 화면이 실제 기기의 화면과 완전히 같지 않기 때문에 
이전 Input PR이나 여기처럼 개발자 도구 상의 특정 기기를 기준으로 잡으면 
실제 동작과 100% 일치한다는 보장을 하기 어려울 거 같습니다
    
제가 가진 기기로 에뮬레이터와 실제 기기 비교 했을 때는 대략 15px~50px 사이 차이 나네요

### 2. 단위 변경 

저 여기 이해를 못해서 시간이 좀 걸렸는데................ `rem`이 상대단위 아닌가요..?
`rem`말고 다른 상대단위를 말하시는 건가요??

**Comment by nijuy** [comment]
> 저는 %, vw, vh 같은 단위를 말씀드리려 했던 거였어요!

말씀하신 "모바일 기기에서 컴포넌트의 크기가 달라보일 수 있다는 점"을 실제로 확인해본 게 아니라서
어느 정도로 문제가 될 지 예상하기가 어렵쥐만,, 저도 체리 말대로 본문 14 pro max 사진 보면 괜찮아보여서 일단 기준만 바꿔보면 어떨까 싶어요

> breakpoint는 30rem이 480px이라 요 정도로 두면 좋을 것 같네요!

넵 좋습니다 ~.~

**Comment by 2wndrhs** [comment]
현재 사용되고 있는 `rem` 단위를 `%`, `vw`, `vh` 단위로 변경하는 작업이 리소스가 많이 들어갈 것 같아 저희 상황에서는 breakpoint를 늘리는 것이 좋은 방향인 것 같네요!

저도 480px로 breakpoint를 늘리는 쪽에 한 표 던지겠습니다
